### ISSUE TITLE
Entity creation in CWRC-Writer

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-PublicEntityDialogs#12]
Add a button (label: 'Create Entity') in the cwrc-writer entity lookup form that opens the Islandora CWRC Entity Creation forms in a new browser window and passes as a URL parameter the collection in which the new entity should be created. e.g., http://cwrc.ca/entity/create?collection='SOMECOLLECTIONNAME'

The choice of entity collection is made in CWRC-Writer the first time the user tries to add an entity (Text:  'Please choose a CWRC collection in which to create the entity.  Your choice will be used for all new entities created in this editing session.').  We save their choice so we can use it for any subsequent entity creations in the same edit session.  Question:  need to supply the list from which they select.  I think we'd talked about his before and Jeff had suggested a json config file in the CWRC-Writer.  If so, that's fine.

Question:  Just before opening the new browser window, should we say something like 'After you've created the entity, please return to this window and click the 'Find Entity' button to run the search again.  You may then choose your newly created entity from the refreshed results.'

The CWRC-Writer does not need to deal with authentication when opening the entity creation window , or for any entity lookups.

**Comment by jefferya** [comment]
For entity creation:
* {server_name}/{base_path}/{collection_pid}/manage/overview/ingest
  * where {base_path} is "islandora/object/"

E.g. http://beta.cwrc.ca/islandora/object/cwrc%3AorganizationEntityCollection/manage/overview/ingest

Proposal for defining a list of collections:
* add to an module admin interface
* Options for how the list is communicated to the CWRC-Writer:
     [ ] API endpoint called by CWRC-Writer (JSON response)
     [ ] Part of the config passed to CWRC-Writer during initialization

* Contents e.g.,
```
{
"entities": {
  "person": {
    "collections": [
      {"CWRC": "PID"},
      {"Orlando": "PID"},
      {"label": "collection_id"}
      ]
    }
  }
}
```

**Comment by ilovan** [comment]
Hi James, 

Re. your question: could we have the window with the entity creation form open smallerand on top of the current window so that it looks like a popup? 

Something like this: 

![screen shot 2017-08-31 at 8 28 22 am](https://user-images.githubusercontent.com/6600070/29928500-6ad328ba-8e26-11e7-8dbe-ecdfacd8d966.png)


I know we talked about this ability being browser dependent, but since we are only supporting Chrome and Firefox anyway, it might be worth it?
I am not very fond of bombarding the user with too many pop-up mesages as they risk to be closed without being read, especially if they are too verbose.


Also, after creating the entity and closing the entity creation form, could we have the entity show up at the top of the lookup dropdown without the user having to refresh the search? (just a nice to have way to go about it, I think; we can live with the refresh if need be, though instead of the text you suggested, I would say a confirmation message llike this would work better after saving the new entity: "Entity saved. Click "FInd entity" in the lookup to locate it.")

**Comment by jchartrand** [comment]
> On Aug 31, 2017, at 10:51 AM, Mihaela Ilovan <notifications@github.com> wrote:
> 
> Hi James,
> 
> Re. your question: could we have the window with the entity creation form open smallerand on top of the current window so that it looks like a popup?
> 
> 
Yes, should be able to.
> Something like this:
> 
>  <https://user-images.githubusercontent.com/6600070/29928500-6ad328ba-8e26-11e7-8dbe-ecdfacd8d966.png>
> I know we talked about this ability being browser dependent, but since we are only supporting Chrome and Firefox anyway, it might be worth it?
> I am not very fond of bombarding the user with too many pop-up mesages as they risk to be closed without being read, especially if they are too verbose.
> 
> 
I’m not sure what you mean by ‘too many pop-up messages’.  Which popup messages do you mean?
> Also, after creating the entity and closing the entity creation form, could we have the entity show up at the top of the lookup dropdown without the user having to refresh the search?
> 
I think it’s likely possible (using some kind of polling in the original window to detect when the other window had finished it’s work), but it would be tricky.  
> (just a nice to have way to go about it, I think; we can live with the refresh if need be, though instead of the text you suggested, I would say a confirmation message llike this would work better after saving the new entity: "Entity saved. Click "FInd entity" in the lookup to locate it.")
> 
> 
I still think some text in the editor, *before opening the popup* to tell them what is about to happen (i.e., a whole new window will open) might help to avoid confusing the user - they might otherwise not be sure where’d they been sent.  I do think you are right that final confirmation text in the popup (i.e., new window) would be great, but if the entity creation forms are now totally separate from the CWRC-Writer and intended for use not just by the CWRC-Writer, but also independently, and possibly by other applications, then it would complicate things to have a CWRC-Writer specific message in the independent forms.

I suggest that you (Mihaela) confirm when we’ve arrived at some consensus on these GitHub issues, at which point you summarize the decisions (ideally by editing the topmost comment in the GitHub issue, but editing it down to just what has been decided, and removing any other old out of date stuff in that top most comment) and then prioritize the issue in the queue (product backlog) for actual development.  In scrum terms you’d be the ‘Product Owner’ and as such you’d take ownership of the ‘product backlog’.

**Comment by ilovan** [comment]
#2
