### ISSUE TITLE
dialog not initializing properly in HTML

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-PublicEntityDialogs#16]
![image.png](https://images.zenhubusercontent.com/5a60ef334b5806bc2bc34ef2/bf29897b-f323-4585-aee8-9cbd06f79cbc)

**Comment by jchartrand** [comment]
Andrew has fixed this - versions of jquery specified in package.json were not the same as versions specified in package-lock.json

**Comment by ilovan** [comment]
@ajmacdonald or @jchartrand 
What dialogs were affected by this?

**Comment by jchartrand** [comment]
Public entity dialogs - the repo in which the issue was created.

**Comment by ilovan** [comment]
Looks to be working now

**Comment by ilovan** [comment]
seems to be fixed in Prod Git-Writer and dev-06
