### ISSUE TITLE
Mini CWRC-Writer entity lookups: users cannot modify the text in the search box 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#17]
Not sure if this is an entity lookup issue (@jchartrand) or a mini-CWRC-Writer issue (@ajmacdonald). 

Please feel free to sort it out amongst yourselves.

**Comment by jchartrand** [comment]
@ajmacdonald <https://github.com/ajmacdonald> I can reproduce the problem, but there’s no error in the console, and I can’t off hand think why the text can’t be edited.  Any early ideas?

**Comment by ajmacdonald** [comment]
There was an issue with jquery modal dialogs (e.g. the mini writer container) preventing the focusin event from firing.

**Comment by ilovan** [comment]
Confirmed

**Comment by ilovan** [comment]
confirmed fixed on dev-06 and prod Git-Writer
