### ISSUE TITLE
Mini CWRC-Writer: still getting the https error when using the lookups, though the lookup and tagging seem to be working.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#18]
This is what I get:
![Screen Shot 2018-01-31 at 12.08.31 PM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/bdd2847e-58f2-4ba2-b5b2-5f6bdaca9877)

This is the repo: https://github.com/ilovan/Jan-2017-SideBySide-Test

Still no sure who should handle these lookups within mini CWRC-Writer issues

**Comment by jchartrand** [comment]
Can you provide a bit more info?  which version of the cwrcWriter, which browser, how you got the error (how we’d reproduce)?  I’m not, for example, sure what you mean when you say ‘though the lookup and tagging seem to be working’.  Other than appearing in the console, how does the error affect the lookups?  i.e., what’s broken?

Is it that you see the error when you single-click on any one of the results, and you also don’t see anything in the fully expanded result?  Which is an error, and I’ll add four new GitHub issues for it in a moment, one for each entity source.

**Comment by ilovan** [comment]
You're right @jchartrand, it's that issue, actually (it was the next on my list of things to test with the developer tools on, but I got confused by it while testing the mini-CWRC-Writer and assumed it had something to do with the lookups being open in the mini editor). 
Thanks for adding the new issues for each of the entity lookups. I am going to close this one now.
