### ISSUE TITLE
Create independent entity management pages

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-PublicEntityDialogs#2]
A question that I’m not sure was ever directly answered (although Susan did say in this thread (https://github.com/cwrc/CWRC-PublicEntityDialogs/wiki/Scoping-Document#entity-modifications):  "I believe that the "Modify" button for editing entities always took one to a separate page. OK to continue with that."):

So, rather than incorporate CWRC entity creation/edit directly into the CWRC-Writer (as a popup) would it make more sense to create independent pages for edit/creation.  That way entities could be created and modified from outside the CWRC-Writer.  And then anytime someone wants to create an entity within the CWRC-Writer they would simply be redirected to these pages in a new tab or window.

**Comment by SusanBrown** [comment]
Yes, absolutely, this is the route we want to go. I think I said yes to this some time back with the proviso that the "separate page" could still be rendered within the CWRC interface, which I assume that it can.

**Comment by jchartrand** [comment]
Since the authentication for the CWRC entity management seems to be separate from CWRC-Writer, and a part of the Drupal(Islandora) code, showing the separate page would I think be done from Drupal (Islandora).  How easy that is I don’t know.  But, however the new entity management pages are eventually incorporated into the CWRC-Writer, I think you are saying the pages could be created now?  I’ll assume so, and move this issue into the ‘Todo’ project column, to be assigned a developer and a milestone.  Please modify/move/expand as needed.

**Comment by SusanBrown** [comment]
@jefferya Only after responding to this, did I see that you said in the Scoping wiki doc that editing had always happened in the dialogs and not on a http page. 

Can we have a quick judgement from you about whether this is a problematic direction to go in? Obviously it means development on the Islandora side, but unless it seems clear to you that it will be a crazy amount of work, this seems fine to me to go this route. Just as people get new screens when they create new items, it would make sense to get a new screen when you want to create an entity. 

That said, it does mean that they would have to click back to the open CWRC-Writer window. @jchartrand I don't quite understand why the editing can't happen in a dialog that loads input boxes based on the XML. The lookups are in a dialog. Couldn't other forms of data entry be generated from the dialog too?

[So sorry that this issue isn't quite ready to be moved on. :( ]

**Comment by jchartrand** [comment]
There at least two reasons I can think of why edit/create dialogs shouldn't be incorporated directly into the cwrc-writer:

1.  It is extra code that has the written, tested, debugged and subsequently maintained. If we can have a single interface for all entity creation/edit then that's clearly better. 

2.  Authentication and communication with the entity service directly through the cwrc-writer might be tricky.  And as we've already seen with the existing entity dialogs there was clearly something difficult to it.

**Comment by SusanBrown** [comment]
It's a shame we didn't have time to work through this this afternoon.

ignorant question: Are the lookups not also separate from the cwrc-writer despite being dialogs? Or are dialogs necessarily integrated? 

1. Could dialogs not all have the same interface? Agreed there should be just one.

Hoping to hear from @jefferya but as I say am not at all opposed to having this managed through a separate interface though am a bit concerned about integration/navigation in CWRC.

**Comment by jchartrand** [comment]
You ask: "Are the lookups not also separate from the cwrc-writer despite being dialogs? Or are dialogs necessarily integrated?"

Yes, the dialogs are separate from the CWRC-Writer, in their own Github repo with a corresponding NPM package, and further, I have been moving the lookup code (http calls to SPARQL endpoint or HTTP rest endpoint) for each lookup (viaf, getty, wikidata, etc.) into independent github repos/npm modules (e.g., https://github.com/cwrc/viaf-entity-lookup   https://www.npmjs.com/package/viaf-entity-lookup).  

But the dialogs do, at the moment, combine both the dialog specific code (bootstrap modals) and the lookup specific code (the HTML form and the http calls) within the dialog ‘component'.  We could separate the lookup specific code , and indeed could even move it into it’s own component, possibly even following the Web Components standard itself (https://www.webcomponents.org/introduction <https://www.webcomponents.org/introduction>) which is fully implemented by Chrome/Opera, and getting close to fully implemented by others: http://jonrimmer.github.io/are-we-componentized-yet/ <http://jonrimmer.github.io/are-we-componentized-yet/> and can be ‘poly filled’ for all browsers).  And, we don’t necessarily have to use the Web Component standard either, but could create our own ‘vanilla’ HTML/JS components (which is what I’ve been working towards with the dialogs as a whole), or use the subset of the Web Component standard that is implemented by most browsers (except Microsoft).   

CWRC web components (for entity lookup and create/edit) could then be embedded in the dialogs or in an independent HTML page, or for that matter, into any HTML page (thereby more easily allowing others to include CWRC entity lookups into their own applications).

I do think that if you are prepared to invest the time in effectively creating a library of CWRC ‘web components’,  it is a *very* good idea.  But, it would take time and would increase code complexity (more GitHub repos, more npm packages, more build code, etc.)  It would, however, more easily allow embedding lookup and entity create/edit into other interfaces, and not just within CWRC but within other projects as well.

**Comment by jefferya** [comment]
@SusanBrown @jchartrand 

I'm lost in the conversation and not understanding the question.

**Comment by jchartrand** [comment]
Should we have a quick Skype with everyone?

**Comment by jefferya** [comment]
I think where I'm lost is my understanding and it seems to be a false understanding (or set of assumptions) is that the main portion of the work involved switching the dialogs to TEI. The discussions in this project seem to indicate a scope beyond that which I'm unaware. Some point raised have significant impacts on user experience on how the interface flows (i.e., how one moves from editing a doc in CWRC-Writer to annotating an entity create one if it doesn't exist (and optionally assigning to a project) and moving back to editing the document.

Are title entities to become TEI? Currently titles are handled very differently in terms of creation and editing compared to person/org/place.

I'll send via e-mail a longer list of what is confusing me.

**Comment by SusanBrown** [comment]
Decision: Mihaela to try to create these

**Comment by jchartrand** [comment]
Mihaela has created a new repository for this:

https://github.com/cwrc/entity-management-forms

**Comment by ilovan** [comment]
I think the details sprinkled through this conversation have all been added to the [Scoping Wiki](https://github.com/cwrc/cwrc-entity-management-forms/wiki/Dialogs-Scoping), so I am closing it now.
