### ISSUE TITLE
Add "Other (manual input - web address)" text box to the entity lookup popup to allow users to link to an entity outside the authorities we link out to in the lookups.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#21]
Ideally, this box woudl check for a well formed URL and pop a warning if the URL does not exist or if the text input is not consistent with an URL syntax

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/f912c055c5b81f7f900ee121aeac4ac9c49f7a2f

**Comment by ilovan** [comment]
confirmed on dev-cwrc-writer

**Comment by ilovan** [comment]
work complete and deployed
