### ISSUE TITLE
Fix security vulnerability

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#23]
https://github.com/cwrc/CWRC-PublicEntityDialogs/network/dependencies

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/81a971d5967883fc01f1147d727f5272e6fb6d83
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/bdb85834290a7927206ea2359c6b22fbb2941fa5
