### ISSUE TITLE
Test-01: Project logos not showing up in the CWRC lookup results

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#26]
I think this is connected to https://github.com/cwrc/cwrc-entity-management-forms-static/issues/561

Can you please look into the reason for it, @ajmacdonald , and if needed - point Brad to additional code to push to test-01?

**Comment by ajmacdonald** [comment]
The reason is that the project lookup isn't setup on test. Compare https://dev-02.cwrc.ca/projects/json-lookup to https://test-01.cwrc.ca/projects/json-lookup

**Comment by ilovan** [comment]
Thanks Andrew - Nia will provide Brad with the documentation for that.

**Comment by ilovan** [comment]
fixed and working on both test-01 and beta
