### ISSUE TITLE
Should entity lookups be encapsulated as Web Components?

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-PublicEntityDialogs#3]
Package up each entity lookup as an html/js component, either 'vanilla' or using the Web Components standard (https://www.webcomponents.org/introduction),  or possibly even both.  The http calls for the lookups are already in their own repos - we could simply add the corresponding HTML/JS to those repos, to make it easier to embed the HTML and related handling for the calls directly into any web page (including into the CWRC-WRiter entity lookup dialog).

**Comment by SusanBrown** [comment]
Decision: not to do this.
