### ISSUE TITLE
Add CWRC  proxy for LGPN Lookup

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#34]

**Comment by ilovan** [comment]
details in pdf attached to the blocked issue.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-PublicEntityDialogs/commit/acc8de85dbccf845405b7d65dcb9891da555549d

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/lgpn-entity-lookup/commit/d97f6ef2ffab6ad046a938a9ab164d1873fb566d
