### ISSUE TITLE
Integrated CWRC_Writer : CWRC entity lookups - fix logo on CWRC entity lookups

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#37]
## Expected Behaviour

reed entities should show up with the REED logo

## Current Behaviour

they appear with the CWRC logo currently

## Steps to Reproduce (for bugs)

1. go to dev-02.cwrc.ca
2. open any CWRC-Writer document > Edit Content
3. Tag person entity > search for "Abnett, William"

The entity for "Abnett, William" is here: https://dev-02.cwrc.ca/islandora/object/reed:personEntityCollection
It's the collection configured to be the REED entity collection in https://dev-02.cwrc.ca/admin/islandora/cwrc_entities_collections

**Comment by ilovan** [comment]
may be an issue with this specific entity, since I could not edit it either. 
https://dev-02.cwrc.ca/islandora/object/reed%3A41e7c0a7-6444-494b-b3b9-17aace4b0d71/ that I just created shows up with the right logo

**Comment by ajmacdonald** [comment]
The entry for Abnett, William is under the cwrc namespace: https://dev-02.cwrc.ca/islandora/object/cwrc%3A1bd7767a-afdc-4300-9ffa-31652e4d9a04
So that's the reason why the cwrc logo is showing up, see https://github.com/cwrc/cwrc-entity-management-forms-static/issues/51
